export const DEFAULT_POINTER_DENSITY_AMOUNT = 80
export const DEFAULT_DENSITY_RENDER_SCALE = 0.4
export const INITIAL_PULSE_HALF_WIDTH = 2
export const INITIAL_PULSE_DENSITY = 150
export const INITIAL_PULSE_VELOCITY_X = 3
export const INITIAL_PULSE_VELOCITY_Y = -1.8
export const INITIAL_PULSE_STEP_DT = 1 / 60
export const INITIAL_PULSE_WARMUP_STEPS = 8
